### ISSUE TITLE
[BUG]: Example 1 projects.all() produces an unhandled exception.

### ISSUE THREAD

**Issue by bmmcwhirt** [snyk-labs/pysnyk#166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

In the example 'api-demo-1-list-projects.py ' (https://github.com/snyk-labs/pysnyk/blob/master/examples/api-demo-1-list-projects.py) the following line produces an invalid field exception.

`for proj in client.organizations.get(org_id).projects.all():`

This may be an access restriction, but the exception should be properly handled and respond with some indication of what the issue actually is.

Exception:
```
Exception has occurred: InvalidFieldValue
Field "totalDependencies" of type int in Project has invalid value None
  File "<string>", line 78, in from_dict
```

Python 3.10.4
pysnyk==0.9.4

### Steps To Reproduce

Run the example code, possibly with limited access.

**Comment by nhempenius** [comment]
Also ran into this issue, seems to be related to the dataclasses where the API returns null instead of 0 for some of the values, I'm sepcifically running into the issue with this value
https://github.com/snyk-labs/pysnyk/blob/master/snyk/models.py#L559   totalDependencies

With Error: mashumaro.exceptions.InvalidFieldValue: Field "totalDependencies" of type int in Project has invalid value None

**Comment by garethr** [comment]
Thanks for reporting. This may require a more general fix, but the specific issue noted above should be resolved in the default branch now and will be in the 0.9.5 release coming shortly. If you run into with other fields please open a new issue.

**Comment by upintheairsheep** [comment]
Hello, sorry for being off topic, but may I please contact you, for an inquiry regarding your LG Google TV? 
Email: kay(split for privacy)vonkam(ditto)yar (at) gmail or my discord at https://discord.gg/wN9Nmh9pWT
